### ISSUE TITLE
Print PDF CSS Styling To-Do

### ISSUE THREAD

**Issue by jenpark-getty** [thegetty/ancient-glass#52]
- [x] One column-> Two Columns
  - [x] Intro (Tassos)
  - [x] History (Budrovich)
  - [x] Appendix 1
  - [x] Appendix 2
  - [x] Glossary
  - [x] Works cited
  - [x] All backmatter
- [x] Get rid of thumbnail pages
- [x] Align ToC page numbers
- [x] Only displaying one image per entry (main view) and having all of the entries run one after the other and having that image be a quarter page rather than full page. Always by default be the first image
- [x] Removing all section landing pages
